### ISSUE TITLE
[announcement] It's WORKING! and surplus notice..

### ISSUE THREAD

**Issue by rojong00** [kocharmPrj/NSS231012#11]
i merged opencv part and server side socket communication part.

and it works on 0419 jinho's PC

i did it at ~/opencv/NSS231012.

if you wanna try on the pc part, you can use output folder in there.

you can run 'NSS231012' files e.g) ./NSS231012

+ there is also some notice
1.bot goes to far when it finds a parking lot and turns in place
 - i think adding function to move backward a little bit on bot
2. i didnt push lib folder including opencv because of it's heavy size (almost 900M)
3. todo : delete unnecessary files
4. todo : decorate README

**Comment by 0419jinho** [comment]
issue fixed except 4 to do : decorate README

**Comment by rojong00** [comment]
END
